// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQy7_pI7j06H1TX5Gf417s0Vzkt_3yrlE',
    appId: '1:497472812617:android:0087377694266c6dec3198',
    messagingSenderId: '497472812617',
    projectId: 'presence-24adf',
    storageBucket: 'presence-24adf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS6AFbVPmlYOEue0rZlv1EYUvdJ2lJtGU',
    appId: '1:497472812617:ios:686d1dfc249e4291ec3198',
    messagingSenderId: '497472812617',
    projectId: 'presence-24adf',
    storageBucket: 'presence-24adf.appspot.com',
    iosClientId: '497472812617-jt1mfbf306c2ofcpjg8gsaq0rcu85srl.apps.googleusercontent.com',
    iosBundleId: 'com.example.presence',
  );
}
